### PR TITLE
Create Functions

### PR DESCRIPTION
**Pull request by garimapahwa**
please merge my pr

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add a readme file explaining your algorithm as well

**Comment by garimapahwa** [comment]
> Add a readme file explaining your algorithm as well

please have a look now

**Comment by garimapahwa** [comment]
> Add a readme file explaining your algorithm as well

please check now

**Review by 072arushi — APPROVED** [review]
Congrats! Your PR has been merged.

**Pull request merged**
