### PR TITLE
binary search cpp added

### PR DESCRIPTION
**Pull request by geetika001**
added binary search code for cpp in the Searching folder where readme and python code are present.
@072arushi please review and accept the PR.

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Please add a ReadMe File explaining the algorithm.

**Comment by geetika001** [comment]
> Please add a ReadMe File explaining the algorithm.

Hey @072arushi I have already added the readme for the same algorithm and python code in it.I just committed the code for cpp in it in the same searching algo folder.Please check.

**Review by 072arushi — APPROVED** [review]
Add ReadMe file explaining the algorithm

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add readme file

**Comment by geetika001** [comment]
readme added.please accept.

**Review by 072arushi — APPROVED** [review]
Congrats! Your PR has been merged

**Pull request merged**
