### PR TITLE
code for shell sort

### PR DESCRIPTION
**Pull request by Nikhila-KS**
code for shell sort along with explanation

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
You need to make 2 different files. One will be a readme file and other will be the code file.

**Comment by Nikhila-KS** [comment]
I created a new pr for readme, pls check

**Comment by Nikhila-KS** [comment]
made the changes, pls review

**Review by 072arushi — APPROVED** [review]
Congrats! Your PR has been merged

**Pull request merged**
