### PR TITLE
insertion_sort.cpp

### PR DESCRIPTION
**Pull request by singhalshreya**
@072arushi pls have a look.

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
You need to add a readme file explaining your algorithm as well.

**Comment by singhalshreya** [comment]
@072arushi di, I am new to open source. Will you pls confirm how to add a readme file?
Is it done by adding a file with name readme.md in patch 1?

**Comment by singhalshreya** [comment]
@072arushi di pls have a look.

**Comment by singhalshreya** [comment]
@072arushi pls check and accept my PR.

**Review by 072arushi — APPROVED** [review]
Congrats! Your PR has been merged

**Pull request merged**
